base_images:
  latest:
    name: cloud-governance
    namespace: ci
    tag: latest
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cloud-governance-dry-run-yes
  always_run: false
  cluster: build06
  container:
    from: latest
  env:
    policy: unattached_volume
  cron: 10 * * * *
  timeout: 8h0m0s
