base_images:
  latest:
    name: cloud-governance
    namespace: ci
    tag: latest
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cloud-governance-tagging
  capabilities:
  - intranet
  cron: 0 */2 * * *
  restrict_network_access: false
  steps:
    test:
    - ref: openshift-qe-cloud-governance-tagging-ecoeng-01
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: aws-cloud-governance-perf-dept
