base_images:
  latest:
    name: cloud-governance
    namespace: ci
    tag: latest
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: cloud-governance-dry-run-yes
  steps:
    test:
    - ref: openshift-qe-cloud-governance-perf-dept
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: cloud-governance-ping
